version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  gateway:
    depends_on:
      - app
    build:  ./gateway/GateWay
    restart: on-failure
      # env_file: ./.env
    ports:
        - 8888:8888
  
  app:
    build: ./eurekaServer/Eureka_Server
    restart: on-failure
    # env_file: ./.env
    ports:
      - "8761:8761"
    # environment:
    #   SPRING_APPLICATION_JSON: '{
    #     "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
    #     "spring.datasource.username" : "$MYSQLDB_USER",
    #     "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
    #     "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #     "spring.jpa.hibernate.ddl-auto" : "update" }'
  client:
    depends_on:
        - mysqldb
        - app
    build:  ./client/Client
    restart: on-failure
    ports:
        - "8088:8088"
    environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/clients?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "",
          "spring.jpa.hibernate.ddl-auto" : "update"}'     
    
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  voiture:
    depends_on:
      - mysqldb
      - app
      - client
    build:  ./voiture/voiture
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/voitures?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "",
          "spring.jpa.hibernate.ddl-auto" : "update"}'

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: